-- SI CREEN QUE ES NECESARIA ALGUNA OTRA TABLA O CAMPO DENTRO DE LAS TABLAS
-- AGREGUENLO.
CREATE DATABASE IF NOT EXISTS spotify2_db;
USE spotify2_db;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS canciones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100) NOT NULL,
    artista VARCHAR(100) NOT NULL,
    album VARCHAR(100),
    duracion VARCHAR(10),
    genero VARCHAR(50)
);

INSERT INTO usuarios (username, password) VALUES ('admin', '123');